reporting: "on"
startuppopupversion: 1
gui:
    theme:
        lightTheme: false
        # activeBorderColor:
        #     - black
        #     - bold
        # inactiveBorderColor:
        #     - black
        selectedLineBgColor:
            - reverse
